core/milvus_storage.go
core/milvus_storage_test.go
core/storage_option.go
internal/util/errorutil/util.go
internal/util/errorutil/util_test.go
internal/util/retry/options.go
internal/util/retry/retry.go
internal/util/retry/retry_test.go

Signed-off-by: xingzhao <xing.zhao@zilliz.com>

Add milvus storage minio service

---

.dockerignore
.github/workflows/main.yaml
Dockerfile
tests/api/milvus_backup.py
tests/base/client_base.py
tests/requirements.txt
tests/testcases/test_backup_e2e.py
tests/testcases/test_create_backup.py
tests/testcases/test_delete_backup.py
tests/testcases/test_get_backup.py
tests/testcases/test_get_restore.py
tests/testcases/test_list_backup.py
tests/testcases/test_restore_backup.py

Add testcase

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/documentation_improvement.yaml
.github/ISSUE_TEMPLATE/enhancement.yaml
.github/ISSUE_TEMPLATE/feature-request.yaml

Add issue template

---

.github/workflows/main.yaml

Update github action

---

tests/checker.py
tests/testcases/test_backup_perf.py

Add perf test

---

.github/workflows/main.yaml

Test backup across instances

---

.github/workflows/main.yaml
core/backup_context.go
core/backup_meta.go
tests/base/client_base.py
tests/testcases/test_create_backup.py
tests/testcases/test_restore_backup.py

Add test cases for empty collection restore

---

.github/workflows/main.yaml
deployment/cluster/values.yaml
deployment/standalone/values.yaml
scripts/uninstall_milvus.sh
tests/base/client_base.py
tests/testcases/test_backup_e2e.py
tests/testcases/test_create_backup.py

Add test for Helm deployment

---

core/backup_context.go
core/backup_meta.go

Signed-off-by: wayblink <anyang.wang@zilliz.com>

fix index get bug and refine get backup response

---

.github/workflows/main.yaml

Update test timeout

---

core/backup_context.go
go.mod
go.sum

Signed-off-by: wayblink <anyang.wang@zilliz.com>

Update bulkinsert timeout logic

---

.github/workflows/main.yaml
deployment/cluster/docker-compose.yml
deployment/cluster/values.yaml
deployment/standalone/docker-compose.yml
deployment/standalone/values.yaml

Update Milvus tag

---

.github/workflows/main.yaml
scripts/export_log_docker.sh
scripts/export_log_k8s.sh

Export Milvus log

---

.github/workflows/release.yaml
.gitignore
.goreleaser.yaml

see: https://github.com/zilliztech/milvus-backup/issues/67

Add release github action workflow

---

.github/workflows/main.yaml
tests/base/client_base.py
tests/testcases/test_restore_backup.py

ci: update run test timeout

---

core/storage/gcp/gcp.go

gcp: replace amz header with goog

---

core/backup_context.go
example/prepare_data.py
example/verify_data.py

Fix not backuo autoID bug

---

tests/base/client_base.py
tests/testcases/test_restore_backup.py

test: add test case for auto id

---

tests/requirements.txt

test: remove unused python lib

---

core/backup_context.go

Fix data duplicate when restore data larger than 10*maxSegmentGroupSize

---

core/backup_context.go
internal/common/workerpool.go
internal/common/workerpool_test.go

common: no longer reuse worker

---

core/paramtable/base_table.go

feat: support absolute config file path

---

.github/ISSUE_TEMPLATE/bug_report.yaml

ci: update issue template

---

tests/base/client_base.py
tests/common/common_func.py
tests/requirements.txt
tests/testcases/test_restore_backup.py

Add new feature test 

---

.github/workflows/main.yaml

ci: add additional files to trigger CI when they are modified

---

cmd/restore.go

issue: https://github.com/zilliztech/milvus-backup/issues/141
/kind bug

Fix bug when restore with collection name using CLI

---

core/backup_impl_create_backup.go

Compatible with empty milvus rootPath

---

.goreleaser.yaml
README.md

doc: add compatibility for milvus and milvus backup

---

core/backup_impl_create_backup.go
core/backup_impl_restore_backup.go
core/backup_meta.go
core/storage/minio_chunk_manager.go

Support cross bucket restore

---

.github/workflows/main.yaml

ci: add test for backup restore cross milvus version

---

.github/workflows/main.yaml

ci: cancel previous runs in the PR when pushed new commits

---

core/backup_impl_create_backup.go

fix empty rootpath

---

core/backup_context.go
core/backup_impl_create_backup.go
core/backup_impl_restore_backup.go

Lazy initial milvus and storage client

---

core/backup_context.go
core/backup_context_test.go
core/backup_impl_create_backup.go
core/backup_impl_restore_backup.go
core/backup_meta.go
example/db_support/prepare_data.py

Fix some bugs and add full_meta

---

tests/testcases/test_restore_backup.py

[test]update test case to support db

---

core/backup_context_test.go
core/backup_impl_restore_backup.go

Fix compatibility to old backup without database info

---

core/backup_impl_create_backup.go

Change some log level to avoid confusion

---

core/paramtable/base_table.go

Hi milvus team, pr for issue https://github.com/zilliztech/milvus-backup/issues/178. 
please review this pr for me, thanks.

support loading minio and milvus config from env

---

core/paramtable/base_table.go

Fix load config bug

---

.github/workflows/release.yaml
.goreleaser.yaml

Add homebrew

---

.github/workflows/main.yaml
tests/base/client_base.py
tests/testcases/test_restore_backup.py

[test]enable multi partitions in br test

---

core/backup_context_test.go
core/backup_impl_create_backup.go

Supports automatic generation of backup names

---

core/milvus_sdk_test.go
example/prepare_data.py
go.mod
go.sum

Support 2.3

---

core/backup_impl_create_backup.go

Compatible to DescribeIndex error message update

---

.github/workflows/nightly.yaml

[ci]Add nightly to run all test on master, 2.3 and 2.2 milvus version

---

core/backup_server.go

Alert for port conflicts

---

core/backup_context.go

Refine getbackup log

---

configs/backup.yaml
core/backup_impl_create_backup.go
core/backup_impl_restore_backup.go
core/paramtable/params.go
core/storage/azure_chunk_manager.go
core/storage/azure_object_storage.go
core/storage/chunk_manager.go
core/storage/options.go
core/storage/types.go

Support cross Azrue container backup

---

configs/backup.yaml
core/backup_impl_create_backup.go
core/backup_impl_restore_backup.go
tests/base/client_base.py

Optimize segment copy

---

.github/workflows/nightly.yaml

[skip e2e]Increase timeout for nightly test

---

configs/backup.yaml
core/backup_impl_restore_backup.go
core/paramtable/params.go

Debug file copy

---

core/backup_context.go
core/backup_impl_create_backup.go
core/paramtable/params.go

Fix backup slow

---

Dockerfile

/kind bug fix
fix https://github.com/zilliztech/milvus-backup/issues/125
* Correct lowercase letters in the "From" section to capital letters
* Fix milvus-backup path in ENTRYPOINT

Modify docker file typo and fix milvus-backup path in ENTRYPOINT

---

core/backup_impl_restore_backup.go
core/storage/minio_chunk_manager.go

fix MinioChunkManager.Exist a exist path return false

---

configs/backup.yaml
core/paramtable/params.go
core/storage/chunk_manager.go
core/storage/minio_chunk_manager.go
core/storage/options.go

rename minio.cloudProvider to minio.storageType

---

core/backup_meta.go

Update list backup rest api

---

core/milvus_sdk_wrapper.go

fix restore not use backup index name

---

core/storage/minio_chunk_manager.go

update minio_chunk_manager Read

---

core/backup_meta.go

return progress=0 when ToRestoreSize=0 and stateCode != SUCCESS

---

tests/api/milvus_backup.py
tests/requirements.txt
tests/testcases/test_delete_backup.py

test: refactor http client for test

---

tests/testcases/test_restore_backup.py

add more json datatype in br test cases

test: add more json datatype in br test cases

---

tests/common/common_func.py
tests/requirements.txt
tests/testcases/test_restore_backup.py

test: add float16 and brain float16 datatype for br

---

tests/testcases/test_restore_backup.py

test: add case to check ts order after restore

---

core/backup_context.go
core/backup_impl_create_backup.go
core/backup_meta.go
core/backup_meta_manager.go

Support backup progress

---

core/backup_impl_restore_backup.go

fix: repair delete case

---

core/storage/local_chunk_manager.go

Fix: mkdir before copying file for local chunk manager

---

Dockerfile

chore: Update Dockerfile to install ca-certificates

---

core/backup_impl_restore_backup.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml

fix cross restore path

---

.github/workflows/main.yaml
.github/workflows/nightly.yaml
.github/workflows/perf.yaml

ci: update actions/upload-artifact version

---

tests/requirements.txt
tests/testcases/test_restore_backup.py

test: add test cases for text match feature

---

README.md

1. **Example for Syncing MinIO with AWS S3**
- Added an example in the `README.md` to demonstrate how to sync MinIO with an AWS S3 bucket.
- Since AWS S3 is widely used, this example should help others avoid the trial-and-error process I went through. Hopefully, it saves time and effort for anyone setting this up.
2. **Detailed Configuration Table**
- Introduced a configuration table that lists all the available options with detailed descriptions.
- Config comments in the file can be _**easy to overlook**_, so this table provides a clearer, centralized reference.
These updates aim to make the setup process smoother and more user-friendly, especially for first-time users. Let me know if there’s anything else you'd like to see added or improved!

Update README.md to add examples and configurations table.

---

.github/workflows/release.yaml

related: https://github.com/zilliztech/milvus-backup/issues/452

ci: add arm image publish

---

core/backup_impl_create_backup.go

use segment info after flush

---

.github/workflows/main.yaml
deployment/standalone/rbac-values.yaml
example/prepare_data.py
example/prepare_rbac.py
example/verify_data.py
example/verify_rbac.py

test: add rbac backup restore check in ci

---

core/paramtable/params.go

Issue: [#442 ](https://github.com/zilliztech/milvus-backup/issues/442)

Remove all leading slashes from minio rootPath

---

tests/testcases/test_restore_backup.py

test: add restore v2 test case

---

core/backup_impl_restore_backup.go
core/restore/rbac.go
core/restore/rbac_test.go

restore/rbac: skip exited grant

---

.github/mergify.yml

mergify: edit condition to fit 2.5

---

core/client/grpc.go
core/restore/collection.go

restore: use partition num in backup if partition key was set

---

core/restore/collection.go

restore: improve log format

---

core/client/grpc.go
core/client/grpc_test.go
internal/common/aimd_limiter.go
internal/common/aimd_limiter_test.go

common, client: add aimd rate limiter for some rpc

---

.github/workflows/nightly.yaml
scripts/get_latest_tag.py

test: fix nightly github action

---

core/meta/backup_meta_manager.go

meta: set progress to 0 when total size is 0

---

.github/workflows/release.yaml
.goreleaser.yaml
Dockerfile
Makefile

*: improve build workflow

---

scripts/get_latest_tag.py

ci: refine get_latest_tag.py script

---

core/restore/collection.go

restore: restore only meta if meta-only flag is set

---

.github/dependabot.yml
.github/mergify.yml
.github/workflows/main.yaml
.github/workflows/nightly.yaml
deployment/standalone/docker-compose-tei.yml
scripts/check_healthy.sh
tests/check_embedding_service.py
tests/conftest.py
tests/requirements.txt
tests/testcases/test_restore_backup.py
tests/utils/util_pymilvus.py

test: add text embedding function test

---

.github/workflows/nightly.yaml

ci: fix nightly for text embedding function test

---

.github/workflows/main.yaml
.github/workflows/nightly.yaml
.gitignore
deployment/standalone/docker-compose-rbac.yml
deployment/standalone/user.yaml
tests/base/client_base.py
tests/common/common_type.py
tests/conftest.py
tests/pytest.ini
tests/testcases/test_restore_backup_with_rbac.py

test: add rbac restore testcases

---

scripts/get_image_tag_by_short_name.py

ci: fix get latest tag

---

tests/testcases/test_restore_backup.py

test: add dynamic data for insert

---

tests/base/client_base.py
tests/requirements.txt
tests/testcases/test_restore_backup.py

test: enable backup test cases for json path index after code fix

---

core/storage/mpath/path.go
core/storage/mpath/path_test.go

mpath: allow empty root dir

---

core/backup/collection.go
core/backup/collection_test.go

backup: verify binlog number when run backup

---

deployment/standalone/custom_config.yaml
deployment/standalone/docker-compose.yml
example/prepare_data.py
tests/common/common_func.py

ci: use custom config for deployment

---

core/client/grpc.go
core/client/grpc_test.go

client: add identifier to outgoing ctx

---

core/backup/task.go

backup: improve rpc backup error msg

---

.github/mergify.yml
.github/workflows/main.yaml

ci: add 2.2 and 2.3 as source tag for cross version br

---

core/backup/database.go
core/backup/database_test.go
core/backup/task.go
core/client/grpc.go
core/client/grpc_mock.go
core/client/grpc_test.go

backup, client: check feature before backup

---

core/storage/client.go
core/storage/copy_task.go

storage: improve copy retry logic

---

tests/testcases/test_restore_backup.py

test: add property check after restore

---

tests/testcases/test_restore_backup.py

test: add more case for useV2Restore param

---

core/client/milvus/grpc.go
core/client/milvus/restful.go

Add retry logic when failing to fetch the status of a Bulkinsert task, to improve robustness under transient failures.

milvus: retry on Bulkinsert task status fetch failure

---

core/client/cloud/api.go

cloud: hiding confidential information in logs

---

core/storage/azure.go

storage: use azureAccountName directly in URL instead of  accessKeyID

---

configs/backup.yaml
core/paramtable/params.go
core/restore/collection.go
core/restore/task.go

restore, paramtable: parallelize BulkImport tasks

---

core/backup_context.go
core/meta/backup_meta.go
core/meta/meta.go
core/meta/meta_test.go

meta: support read from level file

---

cmd/restore/restore.go
core/backup/collection.go

cmd/restore: rename restore_index to rebuild_index

---

deployment/standalone/docker-compose-tei.yml
tests/testcases/test_restore_backup.py

sentence-transformers/all-MiniLM-L6-v2 is a lightweight model, more friendly for ci

test: use sentence-transformers/all-MiniLM-L6-v2 model for ci

---

cmd/restore/restore_test.go
core/paramtable/params.go
internal/log/log.go

fix https://github.com/zilliztech/milvus-backup/issues/782

fix(log): correct file logging config

---

.github/workflows/azure.yaml

ci: remove pull_request trigger from azure workflow to avoid secrets access issues
