zilliztech/milvus-backup

core/backup_context.go
=> tolerrant for incorrect flush return segments

core/backup_impl_create_backup.go
Intended to fix https://github.com/zilliztech/milvus-backup/issues/176
I tested it on my side, that seems to help. Just adding a simple handler for the cases where `b.params.MinioCfg.RootPath` is empty. Thanks!
=> [FIX]: Empty b.params.MinioCfg.RootPath handler (S3/Ceph) 

.github/workflows/main.yaml, core/backup_context.go, deployment/cluster/docker-compose.yml, deployment/standalone/docker-compose.yml
=> [ci]Update image tag to 2.3.0-latest

.github/workflows/main.yaml, tests/testcases/test_restore_backup.py
=> [ci]Optimization of ci runtime

.github/workflows/main.yaml, .github/workflows/perf.yaml, tests/common/common_type.py, tests/testcases/test_backup_e2e.py, tests/testcases/test_backup_perf.py
=> [ci]Refine ci

.github/workflows/main.yaml, .github/workflows/nightly.yaml, .github/workflows/perf.yaml, tests/requirements.txt, tests/testcases/test_backup_perf.py
=> [ci]Update perf test

README.md
=> Add installation in README

core/backup_context.go, core/backup_context_test.go, core/paramtable/params.go, core/storage/azure_chunk_manager.go, core/storage/chunk_manager.go, core/storage/local_chunk_manager.go, core/storage/minio_chunk_manager.go, core/storage/types.go
=> Add LocalChunkManager support

.github/workflows/main.yaml, tests/base/client_base.py, tests/base/collection_wrapper.py, tests/common/common_func.py, tests/common/common_type.py, tests/requirements.txt, tests/testcases/test_create_backup.py, tests/testcases/test_get_backup.py, tests/testcases/test_get_restore.py, tests/testcases/test_list_backup.py, tests/testcases/test_restore_backup.py
=> [test]Add test for array data type

cmd/restore.go, core/backup_impl_restore_backup.go
If skip_create_collection is not enabled, the collection will be validated before restoration. Therefore, when using drop_exist_collection, skip_create_collection must be enabled first. However, enabling both skip_create_collection and drop_exist_collection will result in the collection being deleted without being correctly recreated afterwards.
=> Fix enabling both drop_exist_collection and skip_create_collection 

core/backup_context.go, core/backup_impl_create_backup.go, core/backup_meta_manager.go
=> Optimize restore speed with many small segments

.github/workflows/main.yaml, .github/workflows/nightly.yaml, .github/workflows/perf.yaml, tests/base/client_base.py, tests/requirements.txt, tests/testcases/test_restore_backup.py
=> ci: update test env

Makefile, configs/backup.yaml, core/backup_context.go, core/backup_context_test.go, core/backup_impl_create_backup.go, core/backup_impl_restore_backup.go, core/milvus_storage_test.go, core/paramtable/params.go, core/storage/azure_chunk_manager.go, core/storage/azure_object_storage.go, core/storage/chunk_manager.go, core/storage/copier.go, core/storage/local_chunk_manager.go, core/storage/minio_chunk_manager.go, core/storage/options.go, core/storage/types.go, scripts/gen_swag.sh
=> Support cross storage backup/restore

configs/backup.yaml, core/backup_context.go, core/backup_impl_create_backup.go, core/backup_impl_restore_backup.go, core/paramtable/params.go, core/storage/copier.go, docs/cross_storage_backup_restore.md
=> Refine cross storage backup and add doc

core/backup_context.go, core/backup_server.go, core/paramtable/base_table.go, core/paramtable/params.go
- Added command-line parameters for backup MinIO cross-storage.
- 'initBackupSecretAccessKey': Retrieve the configuration of 'minio.backupSecretAccessKey' first.
- Changed "string" to "fmt.Sprint" to fix the "go test -v -test.run TestCreateBackup" failure.
- Swagger: Modified the collection_name parameter in ListBackup to be optional.
=>  Command-line parameters for backup MinIO cross-storage

core/backup_impl_create_backup.go, core/storage/local_chunk_manager.go
=> optimize retry in backup prepare

core/backup_impl_create_backup.go
=> chore: lower log levels from info to debug

.github/mergify.yml, .github/workflows/main.yaml, .github/workflows/nightly.yaml, .github/workflows/perf.yaml, OWNERS, build_image.sh, deployment/cluster/values.yaml, scripts/export_log_docker.sh, scripts/get_image_tag_by_short_name.py, tests/base/client_base.py, tests/testcases/test_restore_backup.py
simplify test cases to reduce ci time
=> test: simplify test cases

.github/mergify.yml, .github/workflows/main.yaml
=> add job name and fix mergify ci-passed rule

tests/requirements.txt, tests/testcases/test_restore_backup.py, tests/utils/util_common.py, tests/utils/util_pymilvus.py
=> test: add testcases for bm25 function

core/restore/collection.go, go.mod
=> restore: fix restore index bug in type check

core/client/grpc.go, core/client/restful.go, core/restore/collection.go
=> client, restore: use end_ts as key instead of end_time

core/backup_impl_restore_backup.go, core/restore/collection.go, core/storage/copier.go
=> *: use path.join instead of manually concatenating paths

core/client/grpc.go
=> client: add aimd limit for create 

.github/dependabot.yml, tests/requirements.txt
- Add Go (gomod) dependency update configuration
- Add Python (pip) dependency update configuration
- Configure dependabot to only create PRs for security vulnerabilities
- Set weekly update schedule for all dependency ecosystems
- Set open-pull-requests-limit to 10 for each ecosystem
=> ci: update dependabot.yml to include Go and Python dependencies and fix some cve

core/backup_impl_create_backup.go, core/client/grpc.go
=> core, client: improve log readability during the flush process

core/restore/collection.go
issue: #606 
if the index is json path index and index name has special characters, we just abandon this index name and recreate it in milvus.
=> fix: Fix the bug that unable to restore json path index

core/storage/azure_chunk_manager.go, core/storage/azure_object_storage.go
When I try to backup using azure, I am getting multiple errors.
Related issue: [#446 ](https://github.com/zilliztech/milvus-backup/issues/446)
PRs worked together are:
[#494 ](https://github.com/zilliztech/milvus-backup/pull/494)
[#495 ](https://github.com/zilliztech/milvus-backup/pull/495)
=> milvus-backup failure for Azure Blob Storage Account

core/backup/collection.go, core/storage/copy_task.go
Prevent semaphore errors from masking actual copy failures by using the original context instead of errgroup's cancelable context for acquisition. Maintains proper cancellation for operations while ensuring semaphore waits aren't interrupted by sibling failures.
=> storage: use original context for semaphore acquisition

core/storage/local.go, core/storage/local_test.go
=> storage: return file info directly when prefix is a file
